services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: mindsdb
      POSTGRES_PASSWORD: mindsdb
      POSTGRES_DB: mindsdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - kbnet
  mindsdb:
    image: mindsdb/mindsdb:latest
    ports:
      - "47334:47334"
      - "47335:47335"
      - "47337:47337"
    volumes:
      - mindsdb_data:/root/mdb_storage
    depends_on:
      - db
    networks:
      - kbnet

  # server:
  #   image: kbnet-server:latest
  #   depends_on:
  #     - mindsdb
  #     - db
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - .env
  #   networks:
  #     - kbnet

volumes:
  mindsdb_data:
  db_data:

networks:
  kbnet:
