services:
  db:
    container_name: kb_db
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: mindsdb
      POSTGRES_PASSWORD: mindsdb
      POSTGRES_DB: mindsdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - kbnet
  mindsdb:
    container_name: kb_mindsdb
    image: mindsdb/mindsdb:latest
    ports:
      - "47334:47334"
      - "47335:47335"
    volumes:
      - mindsdb_data:/root/mdb_storage
    depends_on:
      - db
    networks:
      - kbnet

  # platform:
  #   container_name: kb_platform
  #   build:
  #     context: .
  #     dockerfile: ./apps/platform/Dockerfile
  #   depends_on:
  #     - server
  #     - db
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - .env
  #   networks:
  #     - kbnet

  # server:
  #   container_name: kb_server
  #   build:
  #     context: .
  #     dockerfile: ./apps/server/Dockerfile
  #   depends_on:
  #     - mindsdb
  #     - db
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - .env
  #   networks:
  #     - kbnet

volumes:
  mindsdb_data:
  db_data:

networks:
  kbnet:
